system: You are a very knowledgeable AI Assistant that will faithfully assist the user with their task.

introduction: |
  Determine if the provided information is corroborated by the given context. Respond with YES if the context substantiates the information, even partially. Answer NO if the context does not support the information.

principles: |
  Guidelines
  - Answer YES when the context provides either direct or indirect evidence supporting the information. Indirect evidence may include contextual implications or inferred connections that reasonably support the information.
  - Answer NO if the context lacks any supportive evidence, clearly contradicts the information, or if the support provided by the context is too vague or speculative to establish a solid connection to the information.
  - Avoid using "partially" in your response. If the context provides any reasonable support (direct or indirect) for the information, consider it as a YES.

  Strictly answer in this format
  [Start of Context]
  ...
  [End of Context]
  [Start of Response]
  ... 
  [End of Response]
  [Start of Explanation]
  ...
  [End of Explanation]
  [Start of Answer]
  ...
  [End of Answer]

examples: |
  Example 1:
  [Start of Context]
  भौतिकी में, चुंबकत्व वह प्रक्रिया है जिसमें एक वस्तु दूसरी वस्तु पर आकर्षण या प्रतिकर्षण बल डालती है। जिन वस्तुओं में यह गुण होता है उन्हें चुंबक कहा जाता है। निकल, लोहा, कोबाल्ट और उनके मिश्र धातुओं में आसानी से पहचानने योग्य चुंबकीय गुण होते हैं। यह ज्ञात है कि सभी वस्तुएं कम या ज्यादा हद तक चुंबकीय क्षेत्र की उपस्थिति से प्रभावित होती हैं।
  [End of Context]
  [Start of Response]
  निकल, लोहा, कोबाल्ट
  [End of Response]
  [Start of Explanation]
  The provided information is corroborated by the context. The context specifically mentions nickel, iron, and cobalt as materials that exhibit recognizable magnetic properties, which directly aligns with the response listing these materials.
  [End of Explanation]
  [Start of Answer]
  YES
  [End of Answer]

  Example 2:
  [Start of Context]
  भौतिकी में, चुंबकत्व वह प्रक्रिया है जिसमें एक वस्तु दूसरी वस्तु पर आकर्षण या प्रतिकर्षण बल डालती है। जिन वस्तुओं में यह गुण होता है उन्हें चुंबक कहा जाता है। निकल, लोहा, कोबाल्ट और उनके मिश्र धातुओं में आसानी से पहचानने योग्य चुंबकीय गुण होते हैं। यह ज्ञात है कि सभी वस्तुएं कम या ज्यादा हद तक चुंबकीय क्षेत्र की उपस्थिति से प्रभावित होती हैं।
  [End of Context]
  [Start of Response]
  लोहा, निकल और कोबाल्ट ही एकमात्र शुद्ध पदार्थ हैं
  [End of Response]
  [Start of Explanation]
  The provided information is not corroborated by the context. While the context mentions iron, nickel, and cobalt as materials with recognizable magnetic properties, it does not support the claim that they are the only pure substances. The statement in the response is not substantiated by the context provided.
  [Start of Explanation]
  [Start of Answer]
  NO
  [End of Answer]

generation: |
  Now, based on the above examples and guidelines, determine if the following information is supported by the context provided. Answer YES or NO.
  * Return the explanation within the [Start of Explanation] and [End of Explanation] tags.
  * Return the answer between [Start of Answer] and [End of Answer] tags.

  [Start of Context]
  {document}
  [End of Context]
  [Start of Response]
  {response}
  [End of Response] 

start_tags: ["[Start of Explanation]", "[Start of Answer]"]
end_tags: ["[End of Explanation]", "[End of Answer]"]