system: You are a very knowledgeable AI Assistant that will faithfully assist the user with their task.

introduction: |
  Your task is to assess the relevance of a given response to a specific query. This evaluation should be conducted methodically by answering two key questions:

principles: |
  1. Subject Matter Relevance: Does the provided response accurately match the subject matter of the user's query? This question aims to determine if the response is directly related to the main topic or issue presented in the query.
  2. Focus and Perspective Addressing: Does the provided response effectively address the focus or perspective on the subject matter as outlined in the user's query? This question seeks to evaluate whether the response not only matches the subject matter but also aligns with the specific angle or concern raised by the user.
  
  For each question, assign a score of 1 point if the response meets the criteria, and 0 points if it does not. After evaluating each question, provide detailed feedback explaining your reasoning behind the scores awarded.

  Conclude your evaluation with a final result, strictly using the following format: 'Total Score: X'. The total score should represent the sum of points assigned for each question, with a maximum possible score of 2 points.
  Only evaluate the response based on the above criteria, do not create new questions.

examples: |
  Example 1:
  [Start of Question]
  जब एक वस्तु दूसरी वस्तु पर आकर्षण या प्रतिकर्षण बल डालती है, तो इस प्रक्रिया को क्या कहा जाता है?
  [End of Question]

  [Start of Response]
  चुंबकत्व
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response directly addresses the subject matter of the query by stating that the process of one object exerting an attraction or repulsion force on another is called "चुंबकत्व" (magnetism). This accurately reflects the topic of the question.)
  - Alignment with Query's Focus Score: 1 (The response effectively addresses the specific focus of the query, which seeks to identify the term for the process of attraction or repulsion between objects. By providing the correct term, "चुंबकत्व," the response meets the user's request directly.)
  [End of Feedback]

  [Start of Score]
  2
  [End of Score]

  Example 2:
  [Start of Question]
  जब एक वस्तु दूसरी वस्तु पर आकर्षण या प्रतिकर्षण बल डालती है, तो इस प्रक्रिया को क्या कहा जाता है?
  [End of Question]

  [End of Response]
  निकल, लोहा, कोबाल्ट और उनके मिश्र धातुओं में आसानी से पहचानने योग्य चुंबकीय गुण होते हैं
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 0 (The response does not directly address the subject matter of the query, which asks for the term describing the process of one object exerting an attraction or repulsion force on another. Instead, it provides information about the magnetic properties of certain metals, which is unrelated to the main topic of the question.)
  - Alignment with Query's Focus Score: 0 (The response fails to address the specific focus of the question. It does not provide the term that describes the process of attraction or repulsion, which is what the user is seeking. Instead, it diverts to discussing materials with magnetic properties, missing the core inquiry.)
  [End of Feedback]

  [Start of Score]
  0
  [End of Score]


  Example 3:
  [Start of Question]
  जब एक वस्तु दूसरी वस्तु पर आकर्षण या प्रतिकर्षण बल डालती है, तो इस प्रक्रिया को क्या कहा जाता है?
  [End of Question]

  [Start of Response]
  आकर्षण और प्रतिकर्षण
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response addresses the subject matter of the query by stating "आकर्षण और प्रतिकर्षण," which refers to the forces involved when one object interacts with another. This is relevant to the process described in the question.)
  - Alignment with Query's Focus Score: 0 (While the terms "आकर्षण" (attraction) and "विकर्षण" (repulsion) are relevant, the response does not provide the specific term or concept that describes the overall process of one object exerting these forces on another, which was asked for in the query. It lacks the clarity needed to fully address the user's request.)
  [End of Feedback]

  [Start of Score]
  1
  [End of Score]

generation: |
  Begin your response by providing the feedback followed by the score. Be as objective as possible.

  [Start of Question]
  {question}
  [End of Question]

  [Start of Response]
  {response}
  [End of Response]

  * Return the feedback within the [Start of Feedback] and [End of Feedback] tags.
  * Return the final score between [Start of Score] and [End of Score] tags.
start_tags: ["[Start of Feedback]", "[Start of Score]"]
end_tags: ["[End of Feedback]", "[End of Score]"]