introduction: |
  Your task is to assess the relevance of a given response to a specific query. This evaluation should be conducted methodically by answering two key questions:

principles: |
  1. Subject Matter Relevance: Does the provided response accurately match the subject matter of the user's query? This question aims to determine if the response is directly related to the main topic or issue presented in the query.
  2. Focus and Perspective Addressing: Does the provided response effectively address the focus or perspective on the subject matter as outlined in the user's query? This question seeks to evaluate whether the response not only matches the subject matter but also aligns with the specific angle or concern raised by the user.
  
  For each question, assign a score of 1 point if the response meets the criteria, and 0 points if it does not. After evaluating each question, provide detailed feedback explaining your reasoning behind the scores awarded.

  Conclude your evaluation with a final result, strictly using the following format: 'Total Score: X'. The total score should represent the sum of points assigned for each question, with a maximum possible score of 2 points.
  Only evaluate the response based on the above criteria, do not create new questions.

examples: |
  Example 1:
  [Start of Question]
  क्या रक्तकण तीन प्रकार के होते हैं?
  [End of Question]

  [Start of Response]
  हाँ
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response directly addresses the question about the types of blood cells.)
  - Alignment with Query's Focus Score: 1 (The response confirms that there are three types of blood cells.)
  [End of Feedback]

  [Start of Score]
  2
  [End of Score]

  Example 2:
  [Start of Question]
  क्या प्रोटॉन का द्रव्यमान इलेक्ट्रॉन के द्रव्यमान से 1845 गुना अधिक होता है?
  [End of Question]

  [Start of Response]
  हाँ, प्रोटॉन का द्रव्यमान इलेक्ट्रॉन से बहुत अधिक होता है।
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response is directly related to the comparison of proton and electron masses.)
  - Alignment with Query's Focus Score: 0 (While the response confirms that the proton's mass is much greater, it doesn't specifically address the 1845 times factor mentioned in the query.)
  [End of Feedback]

  [Start of Score]
  1
  [End of Score]

  Example 3:
  [Start of Question]
  क्या दिल्ली के लोहे के स्तंभ में 99.72 प्रतिशत लोहा है?
  [End of Question]

  [Start of Response]
  दिल्ली का लोहे का स्तंभ एक प्राचीन स्मारक है जो कई शताब्दियों से खड़ा है।
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 0 (The response mentions the iron pillar in Delhi but doesn't address its composition.)
  - Alignment with Query's Focus Score: 0 (The response fails to answer the specific question about the iron content percentage.)
  [End of Feedback]

  [Start of Score]
  0
  [End of Score]

generation: |
  Begin your response by providing the feedback followed by the score. Be as objective as possible.

  [Start of Question]
  {question}
  [End of Question]

  [Start of Response]
  {response}
  [End of Response]

  * Return the feedback within the [Start of Feedback] and [End of Feedback] tags.
  * Return the final score between [Start of Score] and [End of Score] tags.
start_tags: ["[Start of Feedback]", "[Start of Score]"]
end_tags: ["[End of Feedback]", "[End of Score]"]