introduction: |
  Determine if the provided information is corroborated by the given context. Respond with YES if the context substantiates the information, even partially. Answer NO if the context does not support the information.

principles: |
  Guidelines
  - Answer YES when the context provides either direct or indirect evidence supporting the information. Indirect evidence may include contextual implications or inferred connections that reasonably support the information.
  - Answer NO if the context lacks any supportive evidence, clearly contradicts the information, or if the support provided by the context is too vague or speculative to establish a solid connection to the information.
  - Avoid using "partially" in your response. If the context provides any reasonable support (direct or indirect) for the information, consider it as a YES.

  Strictly answer in this format
  [Start of Context]
  ...
  [End of Context]
  [Start of Response]
  ... 
  [End of Response]
  [Start of Explanation]
  ...
  [End of Explanation]
  [Start of Answer]
  ...
  [End of Answer]

examples: |
  Example 1:
  [Start of Context]
  भौतिकी में, चुंबकत्व वह प्रक्रिया है जिसमें एक वस्तु दूसरी वस्तु पर आकर्षण या विकर्षण बल उत्पन्न करती है। जो वस्तुएँ इस गुण को प्रदर्शित करती हैं उन्हें चुंबक कहा जाता है। निकल, लोहा, कोबाल्ट और उनके मिश्रधातुओं में आसानी से पहचानी जाने वाली चुंबकीय गुण होते हैं। यह ज्ञात है कि सभी वस्तुओं को चुंबकीय क्षेत्र की उपस्थिति से किसी न किसी हद तक प्रभावित किया जाता है।
  [End of Context]
  [Start of Response]
  * निकल
  * लोहा
  * कोबाल्ट
  * उनके मिश्रधातुएँ
  [End of Response]
  [Start of Explanation]
  The context directly supports the information by stating "निकल, लोहा, कोबाल्ट और उनके मिश्रधातुओं में आसानी से पहचानी जाने वाली चुंबकीय गुण होते हैं।" This clearly indicates that nickel, iron, cobalt, and their alloys exhibit strong magnetic properties.
  [End of Explanation]
  [Start of Answer]
  YES
  [End of Answer]

  Example 2:
  [Start of Context]
  रक्त या हेम एक शारीरिक तरल पदार्थ है जो रक्त वाहिकाओं के माध्यम से विभिन्न अंगों में निरंतर प्रवाहित होता है। यह मोटा, कुछ चिपचिपा, लाल रंग का तरल जो रक्त वाहिकाओं में बहता है, एक जीवित ऊतक है। यह प्लाज्मा और रक्त कोशिकाओं से बना होता है। प्लाज्मा एक निर्जीव तरल माध्यम है जिसमें रक्त कोशिकाएँ तैरती हैं।
  [End of Context]
  [Start of Response]
  * प्लाज्मा
  * हीमोग्लोबिन
  * श्वेत रक्त कोशिकाएँ
  * लाल रक्त कोशिकाएँ
  [End of Response]
  [Start of Explanation]
  The context mentions plasma and blood cells as components of blood, but it does not specifically list hemoglobin or white blood cells. While red blood cells can be inferred from the mention of blood cells, the response includes components not directly stated in the given context.
  [End of Explanation]
  [Start of Answer]
  NO
  [End of Answer]

generation: |
  Now, based on the above examples and guidelines, determine if the following information is supported by the context provided. Answer YES or NO.
  * Return the explanation within the [Start of Explanation] and [End of Explanation] tags.
  * Return the answer between [Start of Answer] and [End of Answer] tags.

  [Start of Context]
  {document}
  [End of Context]
  [Start of Response]
  {response}
  [End of Response] 

start_tags: ["[Start of Explanation]", "[Start of Answer]"]
end_tags: ["[End of Explanation]", "[End of Answer]"]