system: You are a very knowledgeable AI Assistant that will faithfully assist the user with their task.

introduction: |
  Determine if the provided information is corroborated by the given context. Respond with YES if the context substantiates the information, even partially. Answer NO if the context does not support the information.

principles: |
  Guidelines
  - Answer YES when the context provides either direct or indirect evidence supporting the information. Indirect evidence may include contextual implications or inferred connections that reasonably support the information.
  - Answer NO if the context lacks any supportive evidence, clearly contradicts the information, or if the support provided by the context is too vague or speculative to establish a solid connection to the information.
  - Avoid using "partially" in your response. If the context provides any reasonable support (direct or indirect) for the information, consider it as a YES.

  Strictly answer in this format
  [Start of Context]
  ...
  [End of Context]
  [Start of Response]
  ... 
  [End of Response]
  [Start of Explanation]
  ...
  [End of Explanation]
  [Start of Answer]
  ...
  [End of Answer]

examples: |
  Example 1:
  [Start of Question]
  कौन से पदार्थ मजबूत चुंबकीय गुण प्रदर्शित करते हैं?
  [End of Question]

  [Start of Response]
  मजबूत चुंबकीय गुण प्रदर्शित करने वाले पदार्थ:
  * निकल
  * लोहा
  * कोबाल्ट
  * उनके मिश्रधातुएँ
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response directly addresses materials with strong magnetic properties, which is the exact subject of the query.)
  - Alignment with Query's Focus Score: 1 (The response provides a specific list of materials exhibiting strong magnetic properties, fully addressing the focus of the query.)
  [End of Feedback]

  [Start of Score]
  2
  [End of Score]

  Example 2:
  [Start of Question]
  रक्त के मुख्य घटक क्या हैं?
  [End of Question]

  [Start of Response]
  रक्त के कुछ घटक:
  * प्लाज्मा
  * लाल रक्त कोशिकाएँ
  * हीमोग्लोबिन
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response is related to the components of blood, which matches the subject matter of the query.)
  - Alignment with Query's Focus Score: 0 (While the response lists some blood components, it misses key components like white blood cells and platelets, and includes hemoglobin which is a part of red blood cells rather than a separate main component. Thus, it doesn't fully address the focus of the query on main components.)
  [End of Feedback]

  [Start of Score]
  1
  [End of Score]

  Example 3:
  [Start of Question]
  परमाणु के नाभिक के घटक क्या हैं?
  [End of Question]

  [Start of Response]
  परमाणु की संरचना:
  * इलेक्ट्रॉन
  * ऑर्बिटल्स
  * इलेक्ट्रॉन शेल
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 0 (The response discusses atomic structure but does not specifically address the components of the nucleus, which is the subject of the query.)
  - Alignment with Query's Focus Score: 0 (The response lists parts of an atom's electron structure, completely missing the focus on nuclear components like protons and neutrons.)
  [End of Feedback]

  [Start of Score]
  0
  [End of Score]

generation: |
  Begin your response by providing the feedback followed by the score. Be as objective as possible.

  [Start of Question]
  {question}
  [End of Question]

  [Start of Response]
  {response}
  [End of Response]

  * Return the feedback within the [Start of Feedback] and [End of Feedback] tags.
  * Return the final score between [Start of Score] and [End of Score] tags.
start_tags: ["[Start of Feedback]", "[Start of Score]"]
end_tags: ["[End of Feedback]", "[End of Score]"]