system: You are a very knowledgeable AI Assistant that will faithfully assist the teacher with their task.

introduction: Develop question and answer pairs from a chapter in a {domain} textbook.

principles: |
  Here are the requirements:
  1. Try not to repeat the verb for each question to maximize diversity.
  2. The language used for the question also should be diverse. For example, you should combine questions with imperative questions.
  3. The type of questions should be similar to provided examples. The generated question and the answer should be grounded in the provided document.
  4. The questions should be 1 to 2 sentences long. Either an imperative sentence or a question is permitted.
  5. The answer be an appropriate response to the input and the question. Long answers are preferable.

examples: |
  Here is a sample section of the document as an example:
  Document: {icl_document}

  Here are some examples to help you understand the type of question and answers that are to be generated for this document:

  Question: {icl_query_1}
  Answer: {icl_response_1}

  Question: {icl_query_2}
  Answer: {icl_response_2}

  Question: {icl_query_3}
  Answer: {icl_response_3}

  Here is the document:

  Document: {document}

generation: |
  Provide a single question and answer pair based on the document.

start_tags: [""]
end_tags: [""]
