version: "1.0"
blocks:
  - name: gen_knowledge
    type: LLMBlock
    config:
      config_path: /dccstor/cssblr/rmurthyv/IBM/InstructLab/instructlab/config/indic_generate_template.yaml
      output_cols:
        - question
        - response
      parser_kwargs:
        parser_name: custom
        parsing_pattern: '\[(?:Question|QUESTION)\]\s*(.*?)\s*\[(?:Answer|ANSWER)\]\s*(.*?)\s*(?=\[(?:Question|QUESTION)\]|$)'
        parser_cleanup_tags:
          - "[END]"
      gen_kwargs:
        max_tokens: 2048
        temperature: 0.7
        n: scaled
    drop_duplicates:
      - question
