version: "1.0"
blocks:
  - name: gen_knowledge
    type: LLMBlock
    config:
      config_path: /Users/rudramurthy/Documents/GitHub/instructlab/output/config/indic_generate_template.yaml
      output_cols:
      - output
      gen_kwargs:
        max_tokens: 2048
        temperature: 0.7
        n: scaled
    drop_duplicates:
    - output
