system: You are a very knowledgeable AI Assistant that will faithfully assist the user with their task.

introduction: |
  Your task is to assess the relevance of a given response to a specific query. This evaluation should be conducted methodically by answering two key questions:

principles: |
  1. Subject Matter Relevance: Does the provided response accurately match the subject matter of the user's query? This question aims to determine if the response is directly related to the main topic or issue presented in the query.
  2. Focus and Perspective Addressing: Does the provided response effectively address the focus or perspective on the subject matter as outlined in the user's query? This question seeks to evaluate whether the response not only matches the subject matter but also aligns with the specific angle or concern raised by the user.
  
  For each question, assign a score of 1 point if the response meets the criteria, and 0 points if it does not. After evaluating each question, provide detailed feedback explaining your reasoning behind the scores awarded.

  Conclude your evaluation with a final result, strictly using the following format: 'Total Score: X'. The total score should represent the sum of points assigned for each question, with a maximum possible score of 2 points.
  Only evaluate the response based on the above criteria, do not create new questions.

examples: |
  Example 1:
  [Start of Question]
  "चुम्बकत्व क्या है?
  a) एक रासायनिक प्रतिक्रिया
  b) एक वस्तु द्वारा दूसरी वस्तु पर लगाया गया आकर्षण या प्रतिकर्षण बल
  c) एक जैविक प्रक्रिया
  d) एक प्रकाश प्रक्रिया"
  [End of Question]

  [Start of Response]
  "b) एक वस्तु द्वारा दूसरी वस्तु पर लगाया गया आकर्षण या प्रतिकर्षण बल"
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response directly addresses the subject matter of the query, which is asking about the correct description of "चुम्बकत्व" (magnetism). The option "b" is the correct answer that defines magnetism as a force of attraction or repulsion between objects, matching the query's topic.)
  - Alignment with Query's Focus Score: 1 (The query is asking for the correct option from a list, and the response provides the correct option ("b"). It accurately and effectively addresses the specific focus of the query, which is to identify the proper definition of magnetism.)
  [End of Feedback]

  [Start of Score]
  2
  [End of Score]

  Example 2:
  [Start of Question]
  "चुम्बकत्व क्या है?
  a) एक रासायनिक प्रतिक्रिया
  b) एक वस्तु द्वारा दूसरी वस्तु पर लगाया गया आकर्षण या प्रतिकर्षण बल
  c) एक जैविक प्रक्रिया
  d) एक प्रकाश प्रक्रिया"
  [End of Question]

  [Start of Response]
  a) एक रासायनिक प्रतिक्रिया
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 0 (The response does not accurately address the subject matter of the query. The option "a" describes a chemical reaction, which is unrelated to the concept of "चुम्बकत्व" (magnetism). Therefore, it does not match the main topic of the question.)
  - Alignment with Query's Focus Score: 0 (The query specifically asks for the correct definition of magnetism among the provided options. By selecting "a," the response fails to address the focus of the question, which seeks the appropriate description of magnetism. Instead, it misidentifies magnetism with an incorrect option.)
  [End of Feedback]

  [Start of Score]
  0
  [End of Score]


generation: |
  Begin your response by providing the feedback followed by the score. Be as objective as possible.

  [Start of Question]
  {question}
  [End of Question]

  [Start of Response]
  {response}
  [End of Response]

  * Return the feedback within the [Start of Feedback] and [End of Feedback] tags.
  * Return the final score between [Start of Score] and [End of Score] tags.
start_tags: ["[Start of Feedback]", "[Start of Score]"]
end_tags: ["[End of Feedback]", "[End of Score]"]