system: You are a very knowledgeable AI Assistant that will faithfully assist the user with their task.

introduction: |
  Your task is to assess the relevance of a given response to a specific query. This evaluation should be conducted methodically by answering two key questions:

principles: |
  1. Subject Matter Relevance: Does the provided response accurately match the subject matter of the user's query? This question aims to determine if the response is directly related to the main topic or issue presented in the query.
  2. Focus and Perspective Addressing: Does the provided response effectively address the focus or perspective on the subject matter as outlined in the user's query? This question seeks to evaluate whether the response not only matches the subject matter but also aligns with the specific angle or concern raised by the user.
  
  For each question, assign a score of 1 point if the response meets the criteria, and 0 points if it does not. After evaluating each question, provide detailed feedback explaining your reasoning behind the scores awarded.

  Conclude your evaluation with a final result, strictly using the following format: 'Total Score: X'. The total score should represent the sum of points assigned for each question, with a maximum possible score of 2 points.
  Only evaluate the response based on the above criteria, do not create new questions.

examples: |
  Example 1:
  [Start of Question]
  चुम्बकत्व क्या है, और यह किस प्रकार की प्रक्रिया को दर्शाता है?
  [End of Question]

  [Start of Response]
  चुम्बकत्व एक ऐसी प्रक्रिया है जिसमें एक वस्तु दूसरी वस्तु पर आकर्षण या प्रतिकर्षण बल लगाती है। इसे भौतिकी में एक महत्वपूर्ण गुण माना जाता है, जो चुम्बकत्व का प्रदर्शन करने वाली वस्तुओं में पाया जाता है।
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response directly relates to the subject of the query, which is "चुम्बकत्व" (magnetism).)
  - Alignment with Query's Focus Score: 0 (The query asks not only about "चुम्बकत्व" but also specifically about the "प्रक्रिया" (process) it represents.)
  [End of Feedback]

  [Start of Score]
  1
  [End of Score]

  Example 2:
  [Start of Question]
  चुम्बकत्व क्या है, और यह किस प्रकार की प्रक्रिया को दर्शाता है?
  [End of Question]

  [Start of Response]
  चुम्बक का उपयोग कई प्रकार के उपकरणों में किया जाता है, जैसे इलेक्ट्रिक मोटर, ट्रांसफार्मर, और मैग्नेटिक रेसोनेंस इमेजिंग (MRI) मशीन में। चुम्बकत्व का यह व्यावहारिक उपयोग उद्योगों और चिकित्सा में महत्वपूर्ण भूमिका निभाता है।
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 0 (The response discusses practical applications of magnets in various devices like electric motors and MRI machines, but it does not address the query's main subject, which is "चुम्बकत्व" (magnetism) or the process it represents. )
  - Alignment with Query's Focus Score: 0 (The query specifically asks for an explanation of what magnetism is and the type of process it represents. The response does not provide any explanation or discussion about the nature of magnetism or its underlying process. Instead, it only lists the uses of magnets in devices, which is not aligned with the query's focus.)
  [End of Feedback]

  [Start of Score]
  0
  [End of Score]


  Example 3:
  [Start of Question]
  चुम्बकत्व क्या है, और यह किस प्रकार की प्रक्रिया को दर्शाता है?
  [End of Question]

  [Start of Response]
  चुम्बकत्व एक ऐसी प्रक्रिया है, जिसमें एक वस्तु दूसरी वस्तु पर आकर्षण या प्रतिकर्षण बल लगाती है। इस प्रक्रिया में चुम्बक जैसी वस्तुएं, जैसे लोहा, निकल, कोबाल्ट आदि, एक चुम्बकीय क्षेत्र उत्पन्न करती हैं, जो अन्य वस्तुओं को अपनी ओर खींच सकती हैं या उनसे दूर धकेल सकती हैं। चुम्बकत्व के इस गुण के कारण, वस्तुएं चुम्बकीय क्षेत्र की उपस्थिति से प्रभावित होती हैं।
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (The response is directly related to the subject of the query, "चुम्बकत्व" (magnetism). It provides an explanation of magnetism, defining it as a process involving attraction or repulsion between objects, which is relevant to the topic.)
  - Alignment with Query's Focus Score: 1 (The response effectively addresses the specific perspective of the query, which asks for an explanation of the process represented by magnetism. The response explains how objects like iron, nickel, and cobalt generate a magnetic field, which in turn causes attraction or repulsion. This explanation aligns with the focus of the question, covering both the concept of magnetism and the process it involves.)
  [End of Feedback]

  [Start of Score]
  2
  [End of Score]

generation: |
  Begin your response by providing the feedback followed by the score. Be as objective as possible.

  [Start of Question]
  {question}
  [End of Question]

  [Start of Response]
  {response}
  [End of Response]

  * Return the feedback within the [Start of Feedback] and [End of Feedback] tags.
  * Return the final score between [Start of Score] and [End of Score] tags.
start_tags: ["[Start of Feedback]", "[Start of Score]"]
end_tags: ["[End of Feedback]", "[End of Score]"]